// BOT MESSAGES
export const SEND_BOT_MESSAGE = "SEND_BOT_MESSAGE";
export const SEND_BOT_MESSAGE_SUCCESS = "SEND_BOT_MESSAGE_SUCCESS";
export const SEND_BOT_MESSAGE_FAILED = "SEND_BOT_MESSAGE_FAILED";

// AUTHENTICATION
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_FAILED = "LOGIN_ADMIN_FAILED";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

//ADMIN DASHBOARD
export const ADMIN_LOADING = "ADMIN_LOADING";
export const GET_ADMIN_VALID_QUESTIONS = "GET_ADMIN_VALID_QUESTIONS";
export const GET_ADMIN_INVALID_QUESTIONS = "GET_ADMIN_INVALID_QUESTONS";
export const EDIT_ADMIN_VALID_QUESTIONS = "EDIT_ADMIN_VALID_QUESTIONS";
export const EDIT_ADMIN_INVALID_QUESTIONS = "EDIT_ADMIN_INVALID_QUESTIONS";
export const GET_ADMIN_ANSWERED_QUESTIONS = "GET_ADMIN_ANSWERED_QUESTIONS";

//LIVE CHAT
export const CHECK_ROOM_STATUS_CS = "CHECK_ROOM_STATUS_CS";
export const ROOM_VERIFY_SUCCESS = "ROOM_VERIFY_SUCCESS";

export const LIVE_CHAT_FAILED = "LIVE_CHAT_FAILED";
